<?php
/**
 * @author Dmitrijs Sitovs <info@scandiweb.com / dmitrijssh@scandiweb.com / dsitovs@gmail.com>
 * @copyright Copyright (c) 2015 Scandiweb, Ltd (http://scandiweb.com)
 * @license http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Scandiweb\Menumanager\Block\Adminhtml\Menu\Edit\Tab\Item
 */
?>
<div class="entry-edit">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Assigned Menu Items')?></span></legend>
        <br />
        <?php if ($this->canShowItemGrid()): ?>
            <div id="regular-category-settings" class="regular-category-settings">
                <div class="actions">
                    <button id="scandiweb_menumanager_add_item" class="action-default scalable secondary edit-menu-item"
                            title="Add Item" type="button" onclick="setLocation('<?php echo $block->getNewItemUrl(); ?>'); return false;"
                            data-ui-id="scandiweb-menumanager-add-items-button">
                        <span><?php echo __('Add Item') ?></span>
                    </button>
                </div>
                <a href="<?php echo $block->getUrl(); ?>"></a>
            </div>

            <?php echo $block->getChildHtml('scandiweb_menumanager_item_grid'); ?>
        <?php else: ?>
            <div class="messages">
                <div class="message message-notice">
                    <div><?php /* @escapeNotVerified */ echo __('To create and assign new items, please save menu first.') ?></div>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
</div>
